apiVersion: v2
name: chasewhiterabbit
description: A Helm chart for ChaseWhiteRabbit enterprise application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - web
  - application
  - business
  - enterprise
home: https://chasewhiterabbit.sxc.codes
sources:
  - https://github.com/tiatheone/ChaseWhiteRabbit-Business-Overview
maintainers:
  - name: Tiation
    email: tiatheone@protonmail.com
  - name: Garrett
    email: garrett@sxc.codes
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cert-manager
    version: v1.12.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
